### ISSUE TITLE
Houston, Houston, we have a font license problem here!

### ISSUE THREAD

**Issue by gentooza** [aulasoftwarelibre/Rx-Flappy#9]
@p52safer, @mbritTech!

We need to check the app's **fonts licenses** before continue.

Can we trace them?

**Comment by mbritTech** [comment]
https://github.com/aulasoftwarelibre/Rx-Flappy/tree/master/src/assets/fonts
https://github.com/aulasoftwarelibre/Rx-Flappy/blob/ef32400ea099f342823436e84fde38db35751ef7/src/assets/css/style.css#L17-L25
There you have the fonts. What we have to check?

**Comment by p52safer** [comment]
Oh, the fonts are not free software... it's a problem. I am looking for where the sources were obtained from, to see the full license and its compatibility with GLP v3+. What possibility would there be to change the font, with the developer's permission?

**Comment by gentooza** [comment]
Yes!

By tracing them I mean to search who and how (which license) published the font.
What I'd do is to search the web for the same fonts.
this kind of process is normal when licensing an already developed program where components have been chosen without freedom criteria.

If it's ok for you both, we can:
Confirm which license have fonts
And then think about our options, we can write to <licensing@fsf.org> asking for help also!

**Comment by mbritTech** [comment]
I saw the fonts in dafont ⤵
https://www.dafont.com/back-to-1982.font
https://www.dafont.com/flappybirdy.font

The creator of flappybirdy have this message
https://www.dafont.com/profile.php?user=756192

**Comment by gentooza** [comment]
yes @mbritTech! 
There, in datafont.com downloading and uncompressing the *back-to-1982* font, we get a:
```
This font is copyright (c) Jakob Fischer at www.pizzadude.dk,  all rights reserved. Do not distribute without the author's permission.

Use this font for non-commercial use only! If you plan to use it for commercial purposes, contact me before doing so!
```
doing the same with *flappybirdy* font we get:
```
The FontStruction “FlappyBirdy”
(http://fontstruct.com/fontstructions/show/1026901) by “GeronimoFonts” is
licensed under a All Rights Reserved license ().
```
So both are **closed source** fonts.
We can't publish a free as in freedom program with closed source parts inside.

what can we do?

**Comment by p52safer** [comment]
@gentooza What possibility would there be to change the font, with the permission of the copyright author? We could look for some similar fonts at [Fontlibrary.org](https://fontlibrary.org/en), which are licensed under some free as in freedom licenses.

**Comment by p52safer** [comment]
> @gentooza What possibility would there be to change the font, with the permission of the copyright author? We could look for some similar fonts at [Fontlibrary.org](https://fontlibrary.org/en), which are licensed under some free as in freedom licenses.

Oh, it's tricky, the FlappyBird font has a special character for the bird, I don't know for sure if it's used in the code, but it probably is.

**Comment by mbritTech** [comment]
Yes, maybe the easiest way is to change the font.
But we have to speak with nya.

**Comment by gentooza** [comment]
yes, I agree both of you

So if we want a GPLv3 licensed program, we'd have to:
- [ ] ask Nya if she's agree to chage them
- [ ] search for similar free as in freedom fonts.
- [ ] change them.

is it ok?

if Nya doesn't want, or there is no similar font to use we could look for other options.
what about LGPLv3+? what about Apache2.0?

I encourage you to ask for help.
<licensing@fsf.org> 
https://www.apache.org/foundation/license-faq.html

**Comment by mbritTech** [comment]
okey when we know the nya thoughts we can continue

**Comment by gentooza** [comment]
Well, sorry for the long delay. (exams, holidays...)
This issue is great to realize what we have to care when licensing our code.

Now, for solving it, I think is cool to work on two stages:

1.  We want our software free as in freedom, we want to license it under the GPLv3+, so... We have to look for an alternative to the closed source fonts chosen. (it's the same with images, music, videos, or other artistic content)
2. We want to open our code, but we can assume it has closed source parts. So we can license it under the Apache 2.0 license. a non copyleft license.

What about open 2 new branches, one for GPLV3+ Flappy bird, and other for Apache 2.0 Flappy bird?
volunteers of each one?

cheers!

**Comment by gentooza** [comment]
By the way, I wrote to [licensing@fsf.org](mailto:licensing@fsf.org) but they were not clear enough about using lgplv3, they told me to change the closed source components :-/

**Comment by mbritTech** [comment]
Hi Joa, I hope you enjoy you vacations period and so.

If I understand well, we are going to have two versions of the app with different licenses: GPLV3+ and Apache 2.0.

It's correct?

**Comment by gentooza** [comment]
yes, this is my proposal!

**Comment by mbritTech** [comment]
@gentooza Any name conventions for the branches: camelCase, kebab-case??

Ex; 
GPLV3+FlappyBird, Apache2.0FlappyBird
GPLV3+flappy-bird, Apache-2.0-flappy-bird

**Comment by gentooza** [comment]
I guess we can keep it easy, isn't it?

a _gplv3_ branch
and another _apache2_ one.

I let it done now, so we can start work in every license quick.

Closing!
